Repository flexn-io/renative, pull requests merged in 2024-05, with the labels that each got.

#1521 First try at making UTs
  packages/core/src/projects/__tests__/appConfig.test.ts
  packages/core/src/projects/__tests__/mutations.test.ts
  packages/core/src/projects/__tests__/npm.test.ts
  packages/core/src/projects/__tests__/package.test.ts
  packages/core/src/projects/__tests__/version.test.ts
  packages/core/src/projects/appConfig.ts
  packages/core/src/tasks/__tests__/taskHelpers.test.ts
  packages/core/src/tasks/taskHelpers.ts
  packages/engine-core/src/tasks/bootstrap/__tests__/questionHelpers.test.ts
  packages/engine-core/src/tasks/global/__tests__/takDoctor.test.ts
  packages/engine-core/src/tasks/linking/__tests__/taskLink.test.ts
  packages/engine-core/src/tasks/platform/__tests__/taskPlatformConnect.test.ts
  packages/engine-core/src/tasks/platform/__tests__/taskPlatformEject.test.ts
  packages/engine-core/src/tasks/project/__tests__/taskProjectConfigure.test.ts
Labels: e2e

#1528 add packageReactNativeAndroid tests
  packages/core/src/tasks/__tests__/taskFinder.test.ts
  packages/sdk-react-native/src/__tests__/androidRunner.test.ts
Labels: e2e

#1530 Fix(TemplateStarter): Fix renative icons not appearing for macOS and Web
  packages/app-harness/package.json
  packages/core/src/projects/assets.ts
  packages/engine-rn-electron/package.json
  packages/engine-rn-electron/src/sdk/runner.ts
  packages/engine-rn-next/src/sdk/runner.ts
  packages/template-starter/package.json
  packages/template-starter/renative.json
  packages/template-starter/renative.template.json
  packages/template-starter/src/pages/_document.tsx
  yarn.lock
Labels: e2e

#1539 Fix: RCTScrollViewTV doesn't exists
  packages/config-templates/pluginTemplates/react-native-tvos/overrides.json
Labels: e2e-harness-androidtv, e2e-template-androidtv

#1547 Fix windows platform support
  packages/template-starter/renative.json
Labels: e2e

#1549 Fix(Windows:Runner): Fix web and android path to respective node modules not found
  packages/engine-rn-next/src/sdk/runner.ts
  packages/sdk-react-native/src/androidRunner.ts
  packages/template-starter/renative.json
  packages/template-starter/renative.template.json
Labels: e2e

#1546 bootstrap local repo additional check
  packages/engine-core/src/tasks/bootstrap/questions/installTemplate.ts
Labels: bug, e2e

#1529 Add UT for sdk-android
  packages/sdk-android/src/__tests__/deviceManager.test.ts
  packages/sdk-android/src/deviceManager.ts
Labels: e2e

#1548 Fix create android simulator error
  packages/sdk-android/src/__tests__/deviceManager.test.ts
  packages/sdk-android/src/deviceManager.ts
Labels: e2e

#1543 Fix(iOS:Splash): Harness app splash screen
  packages/app-harness/appConfigs/harness/assets/ios/launch-image.png
  packages/app-harness/renative.json
  packages/app-harness/src/app/index.tsx
  packages/engine-rn/templates/platforms/ios/RNVApp/AppDelegate.mm
  packages/engine-rn/templates/platforms/ios/RNVApp/LaunchScreen.storyboard
  packages/sdk-apple/src/objectiveCParser.ts
Labels: e2e

#1555 Fix missing dependency
  packages/config-templates/renative.templates.json
  packages/sdk-android/src/__tests__/deviceManager.test.ts
  packages/template-starter/renative.template.json
Labels: e2e

#1551 Fix/exclude dirs for webpack
  packages/core/src/schema/configFiles/engine.ts
  packages/core/src/schema/platforms/fragments/base.ts
  packages/engine-rn-electron/renative.engine.json
  packages/engine-rn-electron/src/adapter.ts
  packages/engine-rn-electron/src/index.ts
  packages/engine-rn-web/renative.engine.json
  packages/sdk-webpack/src/adapter.ts
  packages/sdk-webpack/src/config/webpack.config.js
  packages/sdk-webpack/src/env.ts
  packages/sdk-webpack/src/index.ts
Labels: e2e

#1577 Spelling
  packages/core/src/projects/assets.ts
  packages/core/src/templates/index.ts
  packages/engine-core/src/tasks/crypto/taskCryptoDecrypt.ts
  packages/engine-core/src/tasks/crypto/taskCryptoEncrypt.ts
  packages/sdk-apple/src/deviceManager.ts
  packages/sdk-apple/src/fastlane.ts
  packages/sdk-apple/src/runner.ts
  packages/sdk-telemetry/src/tasks/taskTelemetryDisable.ts
  packages/sdk-telemetry/src/tasks/taskTelemetryEnable.ts
  packages/sdk-webos/src/deviceManager.ts
Labels: e2e

#1572 fix(iOS:DefaultSim): Fix simulator prompt not shown when none defined
  packages/sdk-apple/src/__tests__/runner.test.ts
  packages/sdk-apple/src/runner.ts
Labels: e2e

#1563 feat(Android:Settings.gradle): Add ability to inject code on plugin level
  packages/core/jsonSchema/renative-1.0.schema.json
  packages/core/jsonSchema/rnv.app.json
  packages/core/jsonSchema/rnv.plugin.json
  packages/core/jsonSchema/rnv.project.json
  packages/core/jsonSchema/rnv.templates.json
  packages/core/src/schema/platforms/fragments/templateAndroid.ts
  packages/engine-rn/templates/platforms/android/settings.gradle
  packages/sdk-android/src/gradleParser.ts
  packages/sdk-android/src/types.ts
Labels: e2e

#1570 chore(iOS:Splash): Removing old assets for splash image
  packages/app-harness/appConfigs/harness/assets/ios/Assets.xcassets/launch-image.imageset/Contents.json
  packages/app-harness/appConfigs/harness/assets/ios/Assets.xcassets/launch-image.imageset/launch-image.png
  packages/app-harness/appConfigs/harness/assets/ios/Assets.xcassets/launch-image.imageset/launch-image@2x.png
  packages/app-harness/appConfigs/harness/assets/ios/Assets.xcassets/launch-image.imageset/launch-image@3x.png
Labels: e2e

#1571 fix(AndroidTV:TemplateStarter): Fix intial focus and prevent focus loss
  packages/template-starter/src/app/index.tsx
Labels: e2e

#1578 Fix/MainActivity_kt.onCreate via plugin configuration
  packages/sdk-android/src/kotlinParser.ts
  packages/template-starter/renative.json
Labels: e2e
